//Crear Usuarios
###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name" : "Jose",
    "age" : 25,
    "email" : "jose@gmail.com"
}

//Traer todos los usuarios
###
GET http://localhost:9000/api/users HTTP/1.1

//Buscar un usuario
###
GET http://localhost:9000/api/users/64e0830b28f182aacbaf01b8 HTTP/1.1

//Actualizar un usuario
###
PUT  http://localhost:9000/api/users/64e07ad1257a92e1badcfab4 HTTP/1.1
Content-Type: application/json

{
    "name" : "xD",
    "age" : 1000,
    "email" : "jose@gmail.com"
}

//Eliminar un usuario
###
DELETE  http://localhost:9000/api/users/64e07e635428c1012d8bd1dd HTTP/1.1


//=================================================================================================

//Crear Trabajos
###
POST http://localhost:9000/api/jobs HTTP/1.1
Content-Type: application/json

{
    "company" : "Samsung",
    "job" : "DevelopeR Frond-End",
    "payment" : 5000
}